### ISSUE TITLE
[AVM Module Issue]: Invalid for_each argument when using depends_on in module block

### ISSUE THREAD

**Issue by c-baumgartner** [Azure/terraform-azurerm-avm-ptn-alz#127]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.9.0-beta2

### Description

Calling ALZ module without depends_on works without an issue. But when setting a dependency to another module it will fail with the following error:

```text
│ Error: Invalid for_each argument
│ 
│   on .terraform/modules/alz_architecture/main.management_groups.tf line 2, in resource "azapi_resource" "management_groups_level_0":
│    2:   for_each = local.management_groups_level_0
│     ├────────────────
│     │ local.management_groups_level_0 will be known only after apply
│ 
│ The "for_each" map includes keys derived from resource attributes that cannot be determined until apply, and so OpenTofu cannot determine the full set of keys that will identify the instances of this resource.
│ 
│ When working with unknown values in for_each, it's better to define the map keys statically in your configuration and place apply-time results only in the map values.
│ 
│ Alternatively, you could use the -target planning option to first apply only the resources that the for_each value depends on, and then apply a second time to fully converge.
```

We need to have one resource (LogAnalytics Workspace) and one resource group created upfront.

Module call that **is working*:

```hcl
module "alz_architecture" {
  source  = "Azure/avm-ptn-alz/azurerm"
  version = "0.9.0-beta2"

  architecture_name  = local.architecture_name
  parent_resource_id = data.azapi_client_config.current.tenant_id
  location           = local.location

  enable_telemetry             = local.enable_telemetry
  subscription_placement       = local.subscription_placement
  policy_assignments_to_modify = local.policy_assignments_to_modify
}
```

The following call **will fail** with the above error in the plan phase:

```hcl
module "alz_architecture" {
  source  = "Azure/avm-ptn-alz/azurerm"
  version = "0.9.0-beta2"

  architecture_name  = local.architecture_name
  parent_resource_id = data.azapi_client_config.current.tenant_id
  location           = local.location

  enable_telemetry             = local.enable_telemetry
  subscription_placement       = local.subscription_placement
  policy_assignments_to_modify = local.policy_assignments_to_modify

  depends_on = [ 
    module.sentinel_resource_group_core,
  ]
}
```

This is the corresponding architecture definition:

```yaml
  name: rt-infra
  management_groups:
    - archetypes:
        - root
      display_name: "RT"
      exists: false
      id: "rt"
      parent_id: null
    - archetypes:
        - gk-rt-0-0-1
      display_name: "Unstaged"
      exists: false
      id: "unstaged"
      parent_id: rt  
    - archetypes:
        - gk-rt-0-0-1
      display_name: "RT Core Services"
      exists: false
      id: "core-services"
      parent_id: rt
    - archetypes:
        - gk-rt-0-0-1
      display_name: "RT AppZones"
      exists: false
      id: "appzones"
      parent_id: rt
```

### Addition

Commenting out the ALZ module for the first apply, and then commenting it in (including the depends_on) works.

The strange thing is again, there are no dynamic references to the outputs of the other modules. Only one hard coded resource id referencing to the log analytics workspace in the  `policy_assignments_to_modify`

```hcl
  policy_assignments_to_modify = {
    rt = {
      policy_assignments = {
        Deploy-MDFC-SqlAtp = {
          enforcement_mode = "DoNotEnforce"
        }
        Deploy-MDFC-OssDb = {
          enforcement_mode = "DoNotEnforce"
        }
        Audit-ResourceRGLocation = {
          enforcement_mode = "DoNotEnforce"
        }
        # Deploy-MDFC-Config-H224 = {
        #   parameters = {
        #     parameterName = jsonencode({ value = local.sentinal_log_analytics_workspace_module_config_by_name["SentinelCore"].name })
        #   }
        # }
        Deploy-Diag-Logs = {
          parameters = {
            logAnalytics = jsonencode({ value = "/subscriptions/${data.azapi_client_config.current.subscription_id}/resourcegroups/${local.sentinel_core_resource_group_name}/providers/Microsoft.OperationalInsights/workspaces/${local.sentinel_automation_account_name}" })
          }
        }
        Deploy-AzActivity-Log = {
          parameters = {
            logAnalytics = jsonencode({ value = "/subscriptions/${data.azapi_client_config.current.subscription_id}/resourcegroups/${local.sentinel_core_resource_group_name}/providers/Microsoft.OperationalInsights/workspaces/${local.sentinel_automation_account_name}" })
          }
        }
      }
   }
....
```

The two locals are just strings. I have also tried to make the azapi_client_config a pre-req to the ALZ by adding it in the depends_on list, too
