### ISSUE TITLE
[AVM Module Issue]: Policy Assignments and Definitions fail in YAML / Unhelpful Error Message

### ISSUE THREAD

**Issue by pdreker** [Azure/terraform-azurerm-avm-ptn-alz#206]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.11.1

### Description

For some reason I decided to be "that one guy" to use YAML for Policy Assignments and definition (well, the docs suggested this works...). ;-)
I have the following Policy Definition in my local library in YAML:
```yaml
---
name: DenyAction-Diagnostic-Sub
type: Microsoft.Authorization/policyDefinitions
properties:
  displayName: DenyAction Delete Diagnostic Subscription Settings
  mode: All
  description: Deny deleting of Diagnostic Settings on Subscription
  metadata:
    version: 1.0.0
    category: Monitoring
  parameters: {}
  policyRule:
    if:
      contains: /providers/microsoft.insights/diagnosticSettings/subscriptionToLa
      field: id
    then:
      details:
        actionNames:
          - delete
      effect: denyAction
```

The following Policy Assignment tries to use this definition:
```yaml
---
name: DenyAction-Diagnostic
type: Microsoft.Authorization/policyAssignments
properties:
  description: Deny deleting of Diagnostic Settings on Subscription
  displayName: DenyAction Delete Diagnostic Subscription Settings
  notScopes: []
  parameters: {}
  policyDefinitionId: /providers/Microsoft.Authorization/policyDefinitions/DenyAction-Diagnostic-Sub
  nonComplianceMessages:
    - message: Diagnostic Settings on Subscription cannot be deleted.
  scope: ${current_scope_resource_id}
  enforcementMode: null
location: ${default_location}
identity:
  type: None
```

When running `terraform plan` I get the following error:
```
Error: architectureDataSource.Read() Error creating architecture pcs_alz

  with module.alz_architecture.data.alz_architecture.this,
  on .terraform/modules/alz_architecture/main.tf line 1, in data "alz_architecture" "this":
   1: data "alz_architecture" "this" {

Hierarchy.FromArchitecture: recursion error on architecture `pcs_alz` Hierarchy.recurseAddManagementGroup:
error adding management group `pcs_root`: Hierarchy.AddManagementGroup: error getting referenced policy
definition resource ID for policy assignment `DenyAction-Diagnostic` in management group `pcs_root`:
PolicyAssignment.ReferencedPolicyDefinitionResourceId: policy assignment is nil, missing properties     or policy definition ID
```

I had literally spent hours on troubleshooting this, when "on a whim" I used a VSCode Plugin to convert the YAML into the following JSON:
```json
{
  "name": "DenyAction-Diagnostic",
  "type": "Microsoft.Authorization/policyAssignments",
  "properties": {
    "description": "Deny deleting of Diagnostic Settings on Subscription",
    "displayName": "DenyAction Delete Diagnostic Subscription Settings",
    "notScopes": [],
    "parameters": {},
    "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/DenyAction-Diagnostic-Sub",
    "nonComplianceMessages": [
      {
        "message": "Diagnostic Settings on Subscription cannot be deleted."
      }
    ],
    "scope": "${current_scope_resource_id}",
    "enforcementMode": null
  },
  "location": "${default_location}",
  "identity": {
    "type": "None"
  }
}
```

This immediately fixes the error and goes on to create a valid plan:
```
Plan: 245 to add, 0 to change, 0 to destroy.

Changes to Outputs:

[... redacted ...]
─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
```

When checking the detailed plan, it seems, that the PolicyDefinition itself is picked up correctly (name, display name etc.), but it does not have any rules (while the actual definition file has rules). The YAML Policy Assignment fails completely and if "naively" converted to JSON it works. If I also naively convert the defintion to JSON the plan also shows that it now has the rules, as defined in the JSON file.

So there is something wrong with the whole YAML side of things :-D I can live with using JSON, but the documentation actually made me go for YAML (more readability) by suggesting it could be used interchangeably and by using a 1:1 conversion.

Any help appreciated,
Patrick
