### ISSUE TITLE
[AVM Question/Feedback]: Invalid Parent error

### ISSUE THREAD

**Issue by thepaulmacca** [Azure/terraform-azurerm-avm-ptn-alz#229]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Description

I have an existing management group called `TestGroup` that I'd like to deploy an architecture to. This is being called as below:

`data.tf`
```hcl
data "azurerm_management_group" "test_group" {
  name = "TestGroup"
}
```

`main.tf`
```hcl
parent_resource_id = data.azurerm_management_group.test_group.id
```

`custom.alz_architecture_definition.yml`
```yaml
name: custom

management_groups:
  - id: testing
    display_name: Testing
    archetypes:
      - root
    parent_id: TestGroup
    exists: true
```

When I run a plan, I'm getting this error

```hcl
│ Error: Failed to initialize AlzLib
│ 
│   with provider["registry.terraform.io/azure/alz"],
│   on providers.tf line 27, in provider "alz":
│   27: provider "alz" {
│ 
│ Alzlib.Init: error generating architectures: Alzlib.generateArchitectures: error processing architecture custom - management group testing has invalid parent
│ TestGroup
```

How can I define a `parent_resource_id` correctly? If I set it to the `Tenant Root Group`, I get no errors - but anything other than that, I get this error

Am I doing something incorrectly? I'm guessing me mixing providers has something to do with it

Thanks
